name: Generate Language Stats

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow on

jobs:
  generate-language-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Language Stats
        uses: ellerbrock/github-action-repository-language-stats@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

